import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="font-pretendard antialiased">
        <div className="flex min-h-screen flex-col">
          {/* Header 영역 */}
          <Header />
          {/* Main 영역 */}
          <main className="flex-1">{children}</main>

          {/* Footer 영역 */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
