name: "[User - Web] Static"

permissions:
  contents: read

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/user-web/**'
      - 'package.json'
      - '.github/workflows/ci.user-web.static.yml'
      - 'biome.json'
      - 'pnpm-lock.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm check:user-web:ci

      - name: Type Check
        run: pnpm --filter user-web exec tsc --noEmit

